/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.ptit.cnpm.group11.view.importedbooktitle;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import vn.ptit.cnpm.group11.model.BookTitle;
import vn.ptit.cnpm.group11.model.ImportBill;
import vn.ptit.cnpm.group11.model.ImportedBookTitle;

/**
 *
 * @author Admin
 */
public class EnterQuantityFrm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form EnterQuantityFrm
     */
    private ImportBill importBill;
    private BookTitle bookTitle;
    public EnterQuantityFrm(ImportBill importBill, BookTitle bookTitle) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.importBill = importBill;
        this.bookTitle = bookTitle;
        lblBookTitleIdRes.setText(String.valueOf(bookTitle.getId()));
        lblBookTitleNameRes.setText(bookTitle.getName());
        lblAuthorRes.setText(bookTitle.getAuthor());
        lblPublisherRes.setText(bookTitle.getPublisher());
        lblPublicationYearRes.setText(String.valueOf(bookTitle.getPublicationYear()));
        lblUnitPriceRes.setText(String.valueOf(bookTitle.getUnitPrice()));
        addActionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddBookTitle = new javax.swing.JLabel();
        lblUnitPrice = new javax.swing.JLabel();
        lblBookTitleName = new javax.swing.JLabel();
        lblPublicationYear = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblPublisher = new javax.swing.JLabel();
        lblBookTitleId = new javax.swing.JLabel();
        lblBookTitleIdRes = new javax.swing.JLabel();
        lblBookTitleNameRes = new javax.swing.JLabel();
        lblAuthorRes = new javax.swing.JLabel();
        lblPublisherRes = new javax.swing.JLabel();
        lblPublicationYearRes = new javax.swing.JLabel();
        lblUnitPriceRes = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        spnQuantity = new javax.swing.JSpinner();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAddBookTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddBookTitle.setText("Nhập số lượng truyện");

        lblUnitPrice.setText("Đơn giá");

        lblBookTitleName.setText("Tên");

        lblPublicationYear.setText("Năm xuất bản");

        lblAuthor.setText("Tác giả");

        lblPublisher.setText("Nhà xuất bản");

        lblBookTitleId.setText("Mã");

        lblBookTitleIdRes.setText("Mã đầu truyện");

        lblBookTitleNameRes.setText("Tên đầu truyện");

        lblAuthorRes.setText("Tác giả");

        lblPublisherRes.setText("Nhà xuất bản");

        lblPublicationYearRes.setText("Năm xuất bản");

        lblUnitPriceRes.setText("Đơn giá");

        lblQuantity.setText("Số lượng");

        btnConfirm.setText("Xác nhận");

        btnCancel.setText("Huỷ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuantity)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBookTitleId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnitPrice)
                                    .addComponent(lblPublisher)
                                    .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBookTitleName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addComponent(lblPublicationYear, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddBookTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBookTitleNameRes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPublisherRes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAuthorRes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblBookTitleIdRes)))
                                .addGap(108, 108, 108))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblUnitPriceRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPublicationYearRes, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddBookTitle)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookTitleId)
                    .addComponent(lblBookTitleIdRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookTitleName)
                    .addComponent(lblBookTitleNameRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthor)
                    .addComponent(lblAuthorRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPublisher)
                    .addComponent(lblPublisherRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPublicationYear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPublicationYearRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitPrice)
                    .addComponent(lblUnitPriceRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EnterQuantityFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EnterQuantityFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EnterQuantityFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EnterQuantityFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EnterQuantityFrm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblAddBookTitle;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblAuthorRes;
    private javax.swing.JLabel lblBookTitleId;
    private javax.swing.JLabel lblBookTitleIdRes;
    private javax.swing.JLabel lblBookTitleName;
    private javax.swing.JLabel lblBookTitleNameRes;
    private javax.swing.JLabel lblPublicationYear;
    private javax.swing.JLabel lblPublicationYearRes;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblPublisherRes;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JLabel lblUnitPriceRes;
    private javax.swing.JSpinner spnQuantity;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            if (e.getSource().equals(btnCancel)) {
                this.dispose();
            } else if (e.getSource().equals(btnConfirm)) {
                ImportedBookTitle ibt = new ImportedBookTitle();
                ibt.setUnitPrice(bookTitle.getUnitPrice());
                ibt.setQuantity((int)spnQuantity.getValue());
                ibt.setBookTitle(bookTitle);
                boolean isContain = false;
                boolean isEdit = (boolean) btnConfirm.getClientProperty("editMode");
                for (ImportedBookTitle importedBookTitle : importBill.getImportedBookTitleList()) {
                    if (importedBookTitle.getBookTitle().equals(bookTitle)) {
                        if (!isEdit) {
                            importedBookTitle.setQuantity(importedBookTitle.getQuantity() + (int)spnQuantity.getValue());
                        } else {
                            importedBookTitle.setQuantity((int)spnQuantity.getValue());
                        }
                        isContain = true;
                        break;
                    }
                }
                if (!isContain) {
                    importBill.getImportedBookTitleList().add(ibt);
                }
                ImportedBookTitleListFrm ibtlf = new ImportedBookTitleListFrm(importBill);
                ibtlf.setVisible(true);
                this.dispose();
            }
        }
    }
    private void addActionListener() {
        btnConfirm.addActionListener(this);
        btnCancel.addActionListener(this);
    }
    public void setEditMode(boolean editMode) {
        btnConfirm.putClientProperty("editMode", editMode);
    }
}
