/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.ptit.cnpm.group11.view.provider;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import vn.ptit.cnpm.group11.dao.ProviderDAO;
import vn.ptit.cnpm.group11.model.ImportBill;
import vn.ptit.cnpm.group11.model.Provider;
import vn.ptit.cnpm.group11.model.User;
import vn.ptit.cnpm.group11.view.booktitle.SearchBookTitleFrm;

/**
 *
 * @author Admin
 */
public class SearchProviderFrm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form SearchProviderFrm
     */
    private User user;
    private ArrayList<Provider> providers;
    public SearchProviderFrm(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        this.providers = new ArrayList<>();
        addActionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearchProvider = new javax.swing.JLabel();
        lblProviderName = new javax.swing.JLabel();
        txtProviderName = new javax.swing.JTextField();
        btnSearchProvider = new javax.swing.JButton();
        btnAddProvider = new javax.swing.JButton();
        scrllPaneListProvider = new javax.swing.JScrollPane();
        tblProvider = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSearchProvider.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSearchProvider.setText("Tìm kiếm nhà cung cấp");

        lblProviderName.setText("Tên ");

        btnSearchProvider.setText("Tìm kiếm");

        btnAddProvider.setText("Thêm mới");

        tblProvider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblProvider.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên", "Địa chỉ", "Email", "Điện thoại", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrllPaneListProvider.setViewportView(tblProvider);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblProviderName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtProviderName)
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddProvider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchProvider)
                        .addGap(101, 101, 101))))
            .addGroup(layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(lblSearchProvider, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(scrllPaneListProvider)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProviderName)
                    .addComponent(txtProviderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchProvider)
                    .addComponent(btnAddProvider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrllPaneListProvider, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SearchProviderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SearchProviderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SearchProviderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SearchProviderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SearchProviderFrm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProvider;
    private javax.swing.JButton btnSearchProvider;
    private javax.swing.JLabel lblProviderName;
    private javax.swing.JLabel lblSearchProvider;
    private javax.swing.JScrollPane scrllPaneListProvider;
    private javax.swing.JTable tblProvider;
    private javax.swing.JTextField txtProviderName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            if (e.getSource().equals(btnSearchProvider)) {
                if (txtProviderName.getText() != null) {
                    String key = txtProviderName.getText().trim();
                    if (key.isBlank() || key.isEmpty()) {
                        return;
                    }
                    ProviderDAO providerDAO = new ProviderDAO();
                    providers = providerDAO.searchProviderByName(key);
                    String[] columns = {
                        "STT", "Mã", "Tên", "Địa chỉ", "Email", "Điện thoại", "Mô tả"
                    };
                    String[][] values = new String[providers.size()][columns.length];
                    for (int i = 0; i < providers.size(); i++) {
                        values[i][0] = String.valueOf(i + 1);
                        values[i][1] = String.valueOf(providers.get(i).getId());
                        values[i][2] = providers.get(i).getName();
                        values[i][3] = providers.get(i).getAddress();
                        values[i][4] = providers.get(i).getEmail();
                        values[i][5] = providers.get(i).getPhoneNumber();
                        values[i][6] = providers.get(i).getNote();
                    }
                    DefaultTableModel tableModel = new DefaultTableModel(values, columns) {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                            return false;
                        }
                    };
                    tblProvider.setModel(tableModel);
                }
            } else if (e.getSource().equals(btnAddProvider)) {
                AddProviderFrm addProviderFrm = new AddProviderFrm(user);
                addProviderFrm.setVisible(true);
                this.dispose();
            }
            
        }
    }
    private void addActionListener() {
        btnSearchProvider.addActionListener(this);
        btnAddProvider.addActionListener(this);
        tblProvider.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int column = tblProvider.getColumnModel().getColumnIndexAtX(e.getX());
                int row = e.getY() / tblProvider.getRowHeight();
                
                if (row < tblProvider.getRowCount() && row >= 0
                        && column < tblProvider.getColumnCount()
                        && column >= 0) {
                    Provider selectedProvider = providers.get(row);
                    ImportBill importBill = new ImportBill();
                    importBill.setUser(user);
                    importBill.setProvider(selectedProvider);
                    SearchBookTitleFrm sbtf = new SearchBookTitleFrm(importBill);
                    sbtf.setVisible(true);
                    SearchProviderFrm.this.dispose();
                }
            }
        });
    }
}
